### ISSUE TITLE
Are R5, R8, and R9 redundant?

### ISSUE THREAD

**Issue by chaals** [ethereum-oasis/baseline-standard#129]
R5 requires that a "commercial document" is legally binding, R8 that it is signed by authorised parties, and R9 that it is non-repudiable.

For a contract between parties to hold, the agreement must be made between those parties, and where they are organisations rather than physical people, there needs to be at least reasonable belief that the individuals acting are doing so with authority. Otherwise, the agreement presented in documentation is generally legally repudiable.

With D5 and D6 not *requiring* information about who can sign, R8 seems to become untestable in the general case, as well as being logically unnecessary repetition, and R9 effectively asks for something that cannot be determined except by a court coming after the event to overturn it in practice.

**Comment by GoldenBit0** [comment]
2/24/22 Standards Call:
@Therecanbeonlyone1969 please address

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
