### ISSUE TITLE
CORE Spec - Org Management Component - Identity Management

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-standard#20]
**Purpose:**

Describes process requirements for Identity Management.

**Brainstorm**

Need to address below list of processes:

RequestIdentity - #22 - Should

CreateIdentity - Must

RegisterIdentity  - Must

GetRegisteredIdentity  - Must 
Prerequisites and requirements

RequestUpdateIdentity  - Must

UpdateIdentity  - Must

RevokeIdentity  - Must

RequestIdentityPresentation  - Must

RecoverIdentity - Should

**Comment by caleteeter** [comment]
I am starting some brainstorming and collecting some thoughts [here](https://hackmd.io/l2NQN5xAQLyBGXhobmKEYQ)

**Comment by Consianimis** [comment]
Requirements from: https://github.com/ethereum-oasis/baseline-roadmap/issues/174

| # | Component | Requirement Category | Requirement Type |  Requirement |
| - | ------------- | ------------------------- | -------------------- |--------------- |
| 2 | Identity | NFR | Operator **MAY** employ a centralized solution for baseline identities/accounts/workgroups |
| 3 | Org Management | Authentication & Authorization | NFR | Operator **MUST** synchronize workgroup entities and their accounts to the Baseline Global Phone book |
| 4 | Org Management  | Authentication & Authorization | NFR | Operator **MUST** synchronize workgroup entities and their accounts to the Baseline Global Phone book |
| 5 | Org Management  | Authentication & Authorization | NFR | Operator **MAY** add additional operator specific metadata to synchronized Baseline Global Phone book records |
| 6 | Org Management  | Authentication & Authorization | NFR | Operator **MUST NOT** have the ability to change, update or delete Baseline global phonebook records |
