### ISSUE TITLE
CORE Spec - Org Management Component - Identity Management - RequestIdentity

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-standard#22]
1- Use a trustable phonebook to retrieve the organization DID
1.1 - Option 1 (DNS as trust anchor): Use the .well-known DID configuration spec from DIF
1.2 - Elect a trustable authority to manage the phonebook in a centralized way
1.3 - In both solution, identity can be enriched with VCs.
2- Resolve the DID to retrieve the listed services endpoints
2.1 - Baseline endpoints should have the "type" with value "Baseline"

**Comment by Therecanbeonlyone1969** [comment]
Suggested prerequisites before request identity can be called, and we can put these requirements in the relevant identity section:

The following requirements must be fulfilled before the RequestIdentity API can be successfully invoked:
- The requesting entity MUST have a unique identifier
- Any unique identifier MUST be associated with a set of public keys.
- Any unique identifier MUST be discoverable by any 3rd party.
- Any unique identifier MUST be resolvable to its associated public keys used for cryptographic authentication of the unique identifier. 
- A unique identifier used in the Baseline Protocol MUST be resolvable to an endpoint as a URI that identifies the Baseline Protocol Standard as a supported protocol including the supported version(s).
- A unique identifier used in the Baseline Protocol MUST be resolvable to an endpoint as a URI that allows for Baseline Protocol Standard messaging.
- Any unique identifier SHOULD follow the W3C DID Core specification.
- A unique identifier used in the Baseline Protocol MUST be linked to a Legal Entity through a cryptographically signed, cryptographically verifiable, and cryptographically revocable credential based on the public keys associated with the unique identifier of the credential issuer.
- A credential MAY be self-issued.
- The unique identifier of the Legal Entity MUST be the subject of the credential.
- The unique identifier MUST have a credential linking the unique identifier of the issuer to a Legal Entity. 
- The credential SHOULD follow the W3C Verifiable Credential specification.
- The status of a credential MUST be discoverable by any 3rd party.
- The credential SHOULD be discoverable by any 3rd party.
- The presentation of the credential MUST be cryptographically signed by the presenter of the credential, also known as the credential holder.
- The credential holder MUST have a unique identifier.

**Comment by awoie** [comment]
What is the difference between `RequestIdentity` and `CreateIdentity`? IMO, I don't see where a dedicated `RequestIdentity` protocol message is required. Couldn't we just merge whatever people envision for `RequestIdentity` into `CreateIdentity`?

**Comment by awoie** [comment]
Please find my comments below but note that I'm not sure if this belongs to `RequestIdentity` or to `CreateIdentity`. IMO, both might have to be merged.

> Suggested prerequisites before request identity can be called, and we can put these requirements in the relevant identity section:
> 
> The following requirements must be fulfilled before the RequestIdentity API can be successfully invoked:
> 
> * The requesting entity MUST have a unique identifier
> * Any unique identifier MUST be associated with a set of public keys.
> * Any unique identifier MUST be discoverable by any 3rd party.
> * Any unique identifier MUST be resolvable to its associated public keys used for cryptographic authentication of the unique identifier.

Agree with the above.

> * A unique identifier used in the Baseline Protocol MUST be resolvable to an endpoint as a URI that identifies the Baseline Protocol Standard as a supported protocol including the supported version(s).

Couldn't this be part of Baseline Protocol Standard messaging? There will be protocol message that provides you with the Baseline version the endpoint understands.

> * A unique identifier used in the Baseline Protocol MUST be resolvable to an endpoint as a URI that allows for Baseline Protocol Standard messaging.

If we want to be transport-agnostic, what is Protocol Standard messaging? I'd assume we would define the data model of the Baseline protocol messages and then leave it up to the specific transport how these messages are packed. Is this correct?

> * Any unique identifier SHOULD follow the W3C DID Core specification.
> * A unique identifier used in the Baseline Protocol MUST be linked to a Legal Entity through a cryptographically signed, cryptographically verifiable, and cryptographically revocable credential based on the public keys associated with the unique identifier of the credential issuer.
> * A credential MAY be self-issued.

I guess we would need to define the credential schema in the Baseline spec? Or are we assuming the schema will be implementation specific?

> * The unique identifier of the Legal Entity MUST be the subject of the credential.
> * The unique identifier MUST have a credential linking the unique identifier of the issuer to a Legal Entity.

Do you assume that the credential and identifier will be provided to the process? Should we describe the process with inputs/outputs?

> * The credential SHOULD follow the W3C Verifiable Credential specification.

Ok, then we would need to define the schema as well, right?

> * The status of a credential MUST be discoverable by any 3rd party.
> * The credential SHOULD be discoverable by any 3rd party.

IMO, either the registry or the legal entity itself should be able to provide these VCs. Maybe, a high-level flow diagram might help here?

> * The presentation of the credential MUST be cryptographically signed by the presenter of the credential, also known as the credential holder.
> * The credential holder MUST have a unique identifier.

What is the difference between the holder and the requesting party?

In general, I think it would help me to start with an abstract flow diagram.

**Comment by Therecanbeonlyone1969** [comment]
> What is the difference between `RequestIdentity` and `CreateIdentity`? IMO, I don't see where a dedicated `RequestIdentity` protocol message is required. Couldn't we just merge whatever people envision for `RequestIdentity` into `CreateIdentity`?

@awoie ... the reason why there are 2 APIs is driven by different stack operating models. 

- Model 1: The identity requester is ALSO the stack operator in that case only 1 API is necessary
- Model 2: The identity requester is NOT the stack operator in that case you need 2 APIs, one to request the identity from the operator and the second one to actually create the identity

Happy to reduce to 1 API (overloading the API) if you can show that 1 API can accommodate both models, let's do just one. Please, propose.

**Comment by Therecanbeonlyone1969** [comment]
> > * A unique identifier used in the Baseline Protocol MUST be resolvable to an endpoint as a URI that identifies the Baseline Protocol Standard as a supported protocol including the supported version(s).
> 
> Couldn't this be part of Baseline Protocol Standard messaging? There will be protocol message that provides you with the Baseline version the endpoint understands.

@awoie we can just say:

A unique identifier used in the Baseline Protocol MUST be resolvable to an endpoint as a URI.

**Comment by Therecanbeonlyone1969** [comment]
> > * Any unique identifier SHOULD follow the W3C DID Core specification.
> > * A unique identifier used in the Baseline Protocol MUST be linked to a Legal Entity through a cryptographically signed, cryptographically verifiable, and cryptographically revocable credential based on the public keys associated with the unique identifier of the credential issuer.
> > * A credential MAY be self-issued.
> 
> I guess we would need to define the credential schema in the Baseline spec? Or are we assuming the schema will be implementation specific?

Yes, we will have to recommend options but in the end it is up to the implemented what type of legal entity credential they accept.

**Comment by Therecanbeonlyone1969** [comment]
> > * The unique identifier of the Legal Entity MUST be the subject of the credential.
> > * The unique identifier MUST have a credential linking the unique identifier of the issuer to a Legal Entity.
> 
> Do you assume that the credential and identifier will be provided to the process? Should we describe the process with inputs/outputs?
> 
> > * The credential SHOULD follow the W3C Verifiable Credential specification.
> 
> Ok, then we would need to define the schema as well, right?

@awoie ... we could but we do not have to. We can make recommendations for example through a may/should recurement and then make conditional requirements a must where we specify specific schemas. We do not have to though.

**Comment by Therecanbeonlyone1969** [comment]
> > * The status of a credential MUST be discoverable by any 3rd party.
> > * The credential SHOULD be discoverable by any 3rd party.
> 
> IMO, either the registry or the legal entity itself should be able to provide these VCs. Maybe, a high-level flow diagram might help here?

@awoie ... the RevocationList2020 ... you only need to URI and credential id to ascertain the status but not the credential itself. And the 2nd one just says that it would be easier if the whole thing is discoverable then you can use the credentialStatus property for status validation

**Comment by Therecanbeonlyone1969** [comment]
> > * The presentation of the credential MUST be cryptographically signed by the presenter of the credential, also known as the credential holder.
> > * The credential holder MUST have a unique identifier.
> 
> What is the difference between the holder and the requesting party?

Holder might be a delegate of the requesting party.
 
> Further, is it assumed that the DID is provided to the process as an input param, or is it expected to be created by the process?
> 

All is assumed to exist prior to the process.

> In general, I think it would help me to start with an abstract flow diagram.

You are welcome to create one ;-)

@awoie
