### ISSUE TITLE
Subject matter experts: recruit

### ISSUE THREAD

**Issue by AshCos** [ethereum-oasis/baseline-standard#24]

**Comment by Consianimis** [comment]
Requirements:
- Contributors to the standards and specs working group can be technical or non-technical depending on the task.
- Willing to commit to at least 2-3 hours per week.
    (weekly 1hr meeting + specs contribution + peer reviews)
- Moderate understanding of the existing state of the Baseline Protocol and how the protocol can be useful.
    (can be demonstrated by discussing use cases, sharing ideas for improvement of protocol components and exising doc.)
- Moderate experience in one of the following areas API development, specs development and writing, enterprise product development, zk protocols, messaging.
- Willingness to learn and confidence to contribute.

**Comment by Consianimis** [comment]
@AshCos  - Currently we are particularly looking for people with expertise in data transformation and mapping.

**Comment by jack-garvin** [comment]
@AshCos please DM me. I may have a resource for you.
