### ISSUE TITLE
Proposal to change number of reviewers from 3 to 2.

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-standard#27]
**Purpose:**

There are currently three approvers needed on the baseline-standard repo. We agreed during the standards call on the 11th of March to bring that number down to 2. The TSC had already approved the same request on the main baseline repo. According to @humbitious, no need to ask again.

**Comment by Consianimis** [comment]
@Therecanbeonlyone1969, @humbitious - Could one of you implement the settings to reflect the above please ? Thanks.

**Comment by Therecanbeonlyone1969** [comment]
> @Therecanbeonlyone1969, @humbitious - Could one of you implement the settings to reflect the above please ? Thanks.

I agree with this request -- @kthomas @humbitious  -- please submit your vote.

**Comment by Consianimis** [comment]
I believe this has been done.
