### ISSUE TITLE
Add Operating models definitions + respective high level diagrams

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-standard#30]
**Purpose:**

A baseline-compliant implementation can be self-operated or operated by a third party on behalf of many clients.
During the working sessions, we often have to clarify and differentiate those as some requirements may vary depending on the model so I submit a proposal to include:
- definitions of the different operating models in the glossary 
- high level operating models diagrams in the architecture section

**Comment by Therecanbeonlyone1969** [comment]
That is needed ... we need volunteers to do that @Consianimis ... can you recruit 2 ppl to take this on. @humbitious @kthomas ... looking for support in finding ppl for this task.

**Comment by jack-garvin** [comment]
I would like to be assigned to this Issue.  I love doing high-level diagrams!

**Comment by Consianimis** [comment]
@jack-garvin - Could you open a PR to address this issue please ? Please find a buddy from the maintainer team to work on this with you. Thanks
