### ISSUE TITLE
CORE Spec - multi-party data schema

### ISSUE THREAD

**Issue by jack-garvin** [ethereum-oasis/baseline-standard#31]
Proposed requirements/features: data schema

===================================
On Monday, March 15, 2021, 08:42:19 AM CDT, Anaïs Ofranc wrote:  
 @jack-garvin - if two parties have different data models for 'invoices' in their respective systems. Do you think it should be in scope of the protocol specification to state the requirements for :
   
   - agreement on a 'common' data model as a pre-requisite to the baselining process
   - mechanisms to manage the various agreed 'data models' from within the baseline stack
   - 
Or could it be a preferable approach to state this is a part of the integration that should be left for parties to handle?

========================================
Q1 - prerequisite - yes. The protocol should not require any data that does not directly support the process/workflow/transactions. The 'minimum' viable ecosystem should have minimal data requirements.  Similar to the security axiom of the 'minimum required access' at each step of the process. Of course, the data model just needs to be extensible for future revisions.  Also, I like the notion of using data graphs for oracles.

Q2 - internal data management - yes. Any required data, not just minimal data, should be fully accessible (CRUD) at least to the baseline administrator. Don't forget that the client needs to be able to eradicate all of their data when they exit the baselined environment (workflow). The client needs to be able to make data available publically or limited external availability, as necessary. 

So, there is a need for public-facing data management as well (public, private, and internal data).
Example: For registration purposes, you wouldn't need a sales tax authority unless it is required for your KYC compliance. KYC would be a micro-service requiring specific data. You may not want KYC on every workflow partner. Phone book registration is where data management begins.

I think we are going to have to offer a hierarchy of increasing capabilities: basic registration and minimal baseline data requirements all the way to super-deluxe 'everything-as-a-service'.  Something like - Minimal, Basic two-party, Multi-party, and Enterprise levels. Each would carry a data specification to support baselining relative to the number of parties involved in the workflow.

What is the minimum data required for registration? ID and password (DID and private key). Everything else is going to be specific to the workflow data requirements. 'Baselining' is a process that occurs after registration. What is the minimum data needed to 'begin baselining', but not actually 'being baselined'. 

I know this is obvious, but don't require data unless it is absolutely necessary. For every 'required' data element, you need additional support and verification schemes to maintain the data. Always start with a minimum implementation, additional data requirements get defined along the way. As baselining processes become normalized through network growth, you will be adding to the minimal spec (and all levels) as you get mass adoption in the marketplace.

In theory, if not practice, I could set up an elaborate workflow that only involves one entity. Actually, you would model it as if the blockchain and oracles as the other entity. 

Furthermore, I should be able to set up these entities: 1) an 'anonymous' entity (incognito), the ability to include a workflow partner that requires 'absolute anonymity'. 2) an entity that serves as a placeholder for future workflow partners to support the modeling of workflows. Actual workflow partners would assume these 'placeholder' entities as the partners get registered. 3) an entity can use aliases to support the modeling of workflows. This is similar to #2 but instead of setting up live dummy accounts, only an alias is needed from the original registrant.

**Comment by Therecanbeonlyone1969** [comment]
@jack-garvin ... what you are writing is a mixture of use case and non-functional requirements ... all under the heading of a non-functional requirement. Could you please:

- Create a basic use case flow diagram with actors and inputs and outputs
- Create a basic business requirements document for each step in the use case

This would allow the analysis and abstraction of standards relevant vs. implementation-specific components. This will then allow us to answer the very good questions you raise above. At the moment, this is entirely unclear to me from a standards PoV.

**Comment by jack-garvin** [comment]
Sorry for the braindump above. Maybe, it doesn't make a lot of sense from a standards perspective. 

We can just use the Alice & Bob purchasing example but the requirement is multi-party: Alice, Bob, and Acme. 

The multi-party data schema is necessary to support the unique characteristics of the networked process.

**Comment by Therecanbeonlyone1969** [comment]
@jack-garvin ... for everybody's sanity, and ease of understanding, I would prefer a visual representation and written documentation of the requirements. This is the normal standards process:

1. Document Use Case (visual with brief writeup)
2. Extract Business Requirements (writeup)
3. Derive Standards (combines visuals and writeups in a use case and business requirements document and then derives a 2nd standards document)

Strongly encourage that we follow, at least in a light format, this approach. Makes it easier for newcomers to get up to speed.

cc @Consianimis @humbitious @kthomas
