### ISSUE TITLE
Add link to latest editor's draft to README.md (Github frontpage)

### ISSUE THREAD

**Issue by awoie** [ethereum-oasis/baseline-standard#32]
IMO, it would be good if we always had a link to the latest rendered editor's draft of the specification in the README.md.

Where will the latest version of the spec will be deployed? Directly to https://docs.baseline-protocol.org/baseline-protocol-standard/standards ?

**Comment by Consianimis** [comment]
This is a good idea. It could be a good first issue - easy commit to new contributors.

API spec link : https://github.com/ethereum-oasis/baseline-standard/blob/main/api/baseline-api-v1.0-psd01.md
CORE spec link: https://github.com/ethereum-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md

**Comment by awoie** [comment]
Would it make sense to create github-pages to render the latest draft?

**Comment by Therecanbeonlyone1969** [comment]
> (I would also love to see the spec in HTML not Markdown, so we can handle stuff like internal links better...).

Sigh ... not an HTML fan! md works just fine with links. Never had an issue.

**Comment by jack-garvin** [comment]
> (I would also love to see the spec in HTML not Markdown, so we can handle stuff like internal links better...).

I'm using HackMD. It creates the HTML from the markdown file. I asked @humbitious about this a few days ago. He indicated that Markdown is the current standard for project documentation. 

@awoie Would you like to be added to our team?
