### ISSUE TITLE
Simplified diagram of baselines layers and dID interaction. 

### ISSUE THREAD

**Issue by AshCos** [ethereum-oasis/baseline-standard#33]

**Comment by jack-garvin** [comment]
Please assign this to me! We can include this diagram in our scope.

**Comment by Therecanbeonlyone1969** [comment]
@jack-garvin -- please get together with @awoie and @italobb and @caleteeter to properly address this issue. Thank you!

**Comment by jack-garvin** [comment]
Can you or someone Assign us to the Issue?

**Comment by Consianimis** [comment]
@jack-garvin, @AshCos - @awoie is working on #28. Please let us ensure that there is no duplicate work happening as there may be some overlap here.
