### ISSUE TITLE
Baseline-connector requirements

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-standard#36]

**Comment by Therecanbeonlyone1969** [comment]
@Consianimis this sound like an implementation question. Can you please rephrase as part of our established buckets, please, and then close it. Otherwise we have issue spamming

**Comment by Consianimis** [comment]
@Therecanbeonlyone1969 - We discussed this and opened it during the call yesterday, I have not scoped and put content yet. It will be done by Thursday next week. If not, I will close it.
