### ISSUE TITLE
Baseline Specifications - Getting Started - Overview

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-standard#46]
**#Objective**
Provide quick access to Baseline Protocol specifications epics and documentation activities.
We should consider adding content from this epic to the Readme.md of the repo to facilitate onboarding of new contributors.

**#Ways of working**
 - Each spec task should be assigned to a pair - buddysystem - 1 contributor from standard team, 1 from maintainer team.
 - Each spec task must be focused on delivering specification write ups.
 -  Each spec task must be submitted as a PR. 
 - Once a spec task is allocated, assignees have 2 weeks to submit PR.
 - Review time by the team: 1 week.
 - Thursday meetings to be used to discuss change requests and open issues actively being worked on.
 - If no change requests, no review or no 'active' open issues during a given week then no Thursday meeting during that week.
 - Open issues without activity for 2 weeks will be closed (but can be reopened if necessary). 

**#Specifications**

There are currently two specifications in development:

OASIS Spec 1 - The Baseline CORE Specifications document: The document describes the minimal set of business and technical prerequisites, functional and non-functional requirements, together with a reference architecture that when implemented ensures that two or more systems of record can synchronize their system state over a permissionless public Distributed Ledger Technology (DLT) network.

[CORE latest working draft](https://github.com/ethereum-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md)

OASIS Spec 2- The Baseline API & Data Model Specifications document: The document describes the Baseline programming interface and expected behaviors of all instances of this interface together with the required programming interface data model.

[API latest working draft](https://github.com/ethereum-oasis/baseline-standard/blob/main/api/baseline-api-v1.0-psd01.md)

**#Quick Links - Specification Components**

<table>
<tr>
    <th>Component</th>
    <th>Link</th>
    <th>Description</th>
    <th>Roadmap status</th>
  </tr>
<tr>
    <td>Glossary</td>
    <td>#2</td>
    <td>Provides terminology/definitions of key concepts.</td>
    <td>Status: In progress - Main concepts have been defined and reviewed by the team. New keywords should be defined and added as we go.</td>
  </tr>
<tr>
    <td>API Spec</td>
    <td>#37</td>
    <td>Describes the Baseline programming interface and expected behaviors of all instances of this interface together with the required programming interface data model.</td>
    <td>Status: In progress - PRIORITY </td>
  </tr>
<tr>
    <td>CORE Spec - Identity</td>
    <td>#45</td>
    <td></td>
    <td>Status: In progress</td>
  </tr>
<tr>
    <td>CORE Spec - Communication</td>
    <td>#38</td>
    <td>Describes messaging mechanisms between parties' baseline stacks and between systems of records and baseline stacks.</td>
    <td>Status: Started - actively looking for individuals to take the lead on this.</td>
  </tr>
<tr>
    <td>CORE Spec  - Privacy & Confidentiality</td>
    <td>#39</td>
    <td>Describes mechanisms to ensure counterparties confidentiality and shielded private transactions.</td>
    <td>Status - Not started</td>
  </tr>
<tr>
    <td>CORE Spec  - Agreement Execution</td>
    <td>#40</td>
    <td>Describes the functionalities, events and terms required for baselining.</td>
    <td>Status: Started - actively looking for individuals to take the lead on this.</td>
  </tr>
<tr>
    <td>CORE Spec  - Governance</td>
    <td>#41</td>
    <td>Describes the required functionalities to implement governance processes at every functional layer of the Baseline specification.</td>
    <td>Status: Not started </td>
  </tr>
<tr>
    <td>CORE Spec  - Security Considerations</td>
    <td>#42</td>
    <td>Describes security topics that should be important in Baseline implementations but that are NOT requirements. </td>
    <td>Status: Not started </td>
  </tr>
<tr>
    <td>CORE Spec  - Conformance</td>
    <td>#43</td>
    <td>Describes the conformance clauses and tests required to achieve baseline compliant implementations.</td>
    <td>Status: Not started </td>
  </tr>
</table>

**#Quick Links - Documentation**

<table>
<tr>
    <th>Document</th>
    <th>Link</th>
    <th>Description</th>
    <th>Roadmap status</th>
  </tr>
<tr>
    <td>Cookbook</td>
    <td>#29</td>
    <td>Add specification-related content to Cookbook</th>
    <td>Not started</td>
  </tr>
</table>

**Comment by Consianimis** [comment]
High level structure of the specifications - Draft

![image](https://user-images.githubusercontent.com/8512677/112145477-5297b880-8bd2-11eb-9f5d-1dbaff22cd03.png)

**Comment by anaisofranc** [comment]
Note: This issue has been reviewed. PR to be open to add quick links and updated high level spec structure to Readme.md. ETA: mid april so do not close this issue.

**Comment by Consianimis** [comment]
Note: Keep issue open as it is actively being worked on and updated.
