### ISSUE TITLE
Baseline Core V1.0 links don't exist?

### ISSUE THREAD

**Issue by mehranshakeri** [ethereum-oasis/baseline-standard#49]
In this [file](https://github.com/ethereum-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md) in the section "**[baseline-core-v1.0]**" two provided links are broken. (404 not found)
Actually the link to the baseline project in the oasis website doesn't exist. Is this a placeholder? `https://docs.oasis-open.org/baseline`

**Comment by Consianimis** [comment]
@mehranshakeri - Good point - we should update this section to clearly indicate that it is a placeholder.

**Comment by mehranshakeri** [comment]
Thanks. Then I will close this issue.
