### ISSUE TITLE
 CORE Spec - Communication Component - Authentication & Authorization

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-standard#7]
**Purpose:**

Defines the requirements for the Authentication service responsible for establishing and maintaining the connection between verified parties.

**Brainstorm:**

MUST support ‘mutual’ authentication to establish trust between parties. 
MUST have access to a provider of trusted mapping from parties identities to identity keys.

**Comment by Consianimis** [comment]
Requirements from: https://github.com/ethereum-oasis/baseline-roadmap/issues/174

| # | Component | Requirement Category | Requirement Type |  Requirement |
| - | ------------- | ------------------------- | -------------------- |--------------- |
| 2 | Communication | Authentication & Authorization | NFR | Operator **MAY** employ a centralized solution for baseline identities/accounts/workgroups |
| 3 | Communication | Authentication & Authorization | NFR | Operator **MUST** synchronize workgroup entities and their accounts to the Baseline Global Phone book |
| 4 | Communication | Authentication & Authorization | NFR | Operator **MUST** synchronize workgroup entities and their accounts to the Baseline Global Phone book |
| 5 | Communication | Authentication & Authorization | NFR | Operator **MAY** add additional operator specific metadata to synchronized Baseline Global Phone book records |
| 6 | Communication | Authentication & Authorization | NFR | Operator **MUST NOT** have the ability to change, update or delete Baseline global phonebook records |

**Comment by awoie** [comment]
I'm just wondering if this is related to the communication or org management (registry) component? Most of the requirements relate to the phonebook registry.

**Comment by Consianimis** [comment]
@awoie - Good point - I added those requirements under #20
